export default {
  color: {
    ui02: '#f8f8f8',
    ui01: '#ffffff',
    text01: '#121212',
    ui03: '#ededed',
    ui04: '#e0e0e0',
    ui05: '#aeaeae',
    text03: '#767676',
    text02: '#464646',
    brandOrangeDark: '#c36603',
    brandOrange: '#f78100',
    brandOrangeLight: '#fa9e5c',
    brandOrangeLighter: '#ffb383',
    brandBlueDark: '#1b6acc',
    brandBlue: '#458ffd',
    brandBlueLight: '#79aee8',
    brandBlueLighter: '#9ccefa',
    errorRed: '#ff4242',
    errorRedDark: '#cc3535',
  },
  font: {
    headinglarge: {
      fontFamily: 'Roboto',
      fontSize: '42px',
      fontWeight: '300',
      lineHeight: '1.19',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    headingmedium: {
      fontFamily: 'Roboto',
      fontSize: '32px',
      fontWeight: '300',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    headingsmall: {
      fontFamily: 'Roboto',
      fontSize: '24px',
      fontWeight: '300',
      letterSpacing: '0.4px',
    },
    headingxsmall: {
      fontFamily: 'Roboto',
      fontSize: '20px',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    primarynavactive: {
      fontFamily: 'Roboto',
      fontSize: '18px',
      fontWeight: '500',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    bodylarge: {
      fontFamily: 'Roboto',
      fontSize: '18px',
      lineHeight: '1.17',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    primarynavinactive: {
      fontFamily: 'Roboto',
      fontSize: '18px',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    bodyregular: {
      fontFamily: 'Roboto',
      fontSize: '16px',
      lineHeight: '1.5',
      letterSpacing: '0.4px',
      textAlign: 'left',
    },
    bodysmall: {
      fontFamily: 'Roboto',
      fontSize: '14px',
      lineHeight: '1.29',
      letterSpacing: '0.4px',
      textAlign: 'left',
      color: '#666666',
    },
  },
}
